### PR TITLE
Implement BEAR SSL plus server

### PR DESCRIPTION
**Pull request by mikee47**
Works but probably lots of bugs to fix and refinements necessary.

* [ ] With larger file transfers, BR server just hangs because it runs out of TCP send buffer space. No idea why.

### CODE REVIEW

**Comment by slaff** [comment]
@mikee47 Thanks a lot for the great work that you are doing! Wish you Happy New Year and a lot of success :)

And if you have time and want to come to Brussels we can meet next year at Fosdem 2020(1st and 2nd February): https://fosdem.org/2020/. I will be doing a talk about U:Kit - https://fosdem.org/2020/schedule/event/ema_smoke_detector/

**Comment by slaff** [comment]
@mikee47 The HttpServer_ConfigNetwork sample is no longer delivering the json data. The issue is reproducible also without SSL. The problem is not present in `develop`.

The problem can be reproduced calling:
```
curl -vvv http://192.168.13.10/ajax/get-networks
```

**Comment by mikee47** [comment]
I broke it with 58f8df748956660c62d87ca53a3bde541a625ff9 :-(
Looking for a fix...

**Comment by mikee47** [comment]
See https://github.com/SmingHub/Sming/pull/2011

**Pull request merged**
