### PR TITLE
Suggested changes

### PR DESCRIPTION
**Pull request by mikee47**
I've had a quick run through, will look at it in more detail later and try to pin down the reason for re-compilation.

Few thoughts:

* Is there any scope to use C++ references instead of pointers?
* Would this benefit from creating an SSL namespace for everything?
* Instead of global functions, how about a factory class instead with `createExtension()`, `createContext()`, etc? This could be a global pointer `SslImplementation* sslImpl` which is null if SSL isn't enabled, then we could get rid of need for a dummy SSL component.

### CODE REVIEW

**Comment by mikee47** [comment]
Reason for re-compilation is `SSL_DEBUG` changes. Not sure what the fix is though.

**Comment by mikee47** [comment]
Oh, I see now - it's defined in `Sming/component.mk` (as well as `AxtlsSsl`) so I think remove the top-level reference and should be OK.

**Comment by slaff** [comment]
@mikee47 Can you rebase your PR? Sorry for the caused inconvenience :(

**Comment by slaff** [comment]
> Reason for re-compilation is SSL_DEBUG changes. Not sure what the fix is though.

I would need your help here:
- [x] SSL_DEBUG should cause recompilation only of `axtls-8266`. How to describe this in the mk file?
- [x] Changing the value of ENABLE_SSL should relink the application (and compile the needed SSL implementation if not done yet) but without Sming recompilation.

> Oh, I see now - it's defined in Sming/component.mk (as well as AxtlsSsl) so I think remove the top-level reference and should be OK.

That was it! Thanks @mikee47!

**Comment by slaff** [comment]
Initially I had axtls-8266 and the AxtlsSsl implementation in one component. But then decided against it. axtls-8266 is containing Ssl functions and cryptographic functions, that are quite useful. If someone wants to use the cryptographic functions from axtls-8266 but prefer to have dummy ssl implementation having `AxtlsSsl` as a separate component makes this possible.

> Is there any scope to use C++ references instead of pointers?

Not really. So if you can suggest a version with references that would be great

> Would this benefit from creating an SSL namespace for everything?

Sounds like a good idea to me. I can use something like `sming::ssl`. 

> Instead of global functions, how about a factory class instead with createExtension(), createContext(), etc? This could be a global pointer SslImplementation* sslImpl which is null if SSL isn't enabled, then we could get rid of need for a dummy SSL component.

Sounds good to me :) I will try to update the code...

**Pull request closed without merging**
